# Generated by Django 5.2 on 2025-05-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatosPBX',
            fields=[
                ('codigo_unico', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('protocolo', models.CharField(max_length=150)),
                ('data_de_contato', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quem_ligou', models.CharField(blank=True, max_length=150, null=True)),
                ('quem_recebeu_ligacao', models.CharField(blank=True, max_length=150, null=True)),
                ('grupo_discagem_saida', models.CharField(blank=True, max_length=150, null=True)),
                ('duracao_em_segundos', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_do_tronco', models.CharField(blank=True, max_length=150, null=True)),
                ('chamador', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Contato PBX',
                'verbose_name_plural': 'Contatos PBX',
                'ordering': ['-data_de_contato'],
            },
        ),
    ]
