# Generated by Django 5.2 on 2025-05-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_setorchamadorhistorico'),
        ('pbx', '0002_colaboradorealiaschamador'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='colaboradorealiaschamador',
            constraint=models.UniqueConstraint(fields=('nome_errado',), name='unique_nome_errado'),
        ),
    ]
