# Generated by Django 5.2 on 2025-05-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorChamadorHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inicio', models.DateField()),
                ('data_de_saida', models.DateField(blank=True, null=True)),
                ('chamador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.colaboradores')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.setores')),
            ],
        ),
    ]
